#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 13, 2020 04:37:12 PM -03  platform: Windows NT
#    Jun 13, 2020 04:43:58 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import json


def set_Tk_var():
    global casosDengueSemProv
    casosDengueSemProv = tk.StringVar()
    global provincia
    provincia = tk.StringVar()
    global combobox
    combobox = tk.StringVar()
    global casosDengueProvEdad
    casosDengueProvEdad = tk.StringVar()
    global casosDengueProvZika
    casosDengueProvZika = tk.StringVar()
    global casosDengueSemDep
    casosDengueSemDep = tk.StringVar()
    global departamento
    departamento = tk.StringVar()
    global casosDengueEdadDep
    casosDengueEdadDep = tk.StringVar()
    global casosDengueProvDep
    casosDengueProvDep = tk.StringVar()
    global ProvTotalDeng
    ProvTotalDeng = tk.StringVar()
    global ProvTotalZika
    ProvTotalZika = tk.StringVar()
    global DepTotalDeng
    DepTotalDeng = tk.StringVar()
    global DepTotalZika
    DepTotalZika = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscar_por_semana_dep():                              #Función para el botón de buscar por semana de departamento
    print('INTEGRADOR_support.buscar_por_semana_dep')
    sys.stdout.flush()

def buscar_por_semana_prov():                            #Función para el boton de buscar por semana de provincia
    print('INTEGRADOR_support.buscar_por_semana_prov')
    sys.stdout.flush()

def mostrar_total_dep():                                 #Función para mostrar el total por departamento
    print('INTEGRADOR_support.mostrar_total_dep')
    sys.stdout.flush()

def mostrar_total_prov():                                #Función para mostrar el total por provincia
    print('INTEGRADOR_support.mostrar_total_prov')
    sys.stdout.flush()

def buscar_por_edad_dep():                              #Función para buscar por edad (departamento)
    print('INTEGRADOR_support.buscar_por_edad_dep')
    sys.stdout.flush()

def buscar_por_edad_prov():                             #Función para buscar por edad (provincia)
    print('INTEGRADOR_support.buscar_por_edad_prov')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import INTEGRADOR
    INTEGRADOR.vp_start_gui()





